# This is a basic workflow to help you get started with Actions

name: zipscripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # Identify the list of folders that need to be packaged into artifacts
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      
      - name: List the directories in scripts
        id: set-matrix
        run: |
          dirs=("scripts/change1/" "scripts/change2")
          printf -v dirs_d ',\"%s\"' "${dirs[*]}"
          dirs_d=${ids_d:1}   
          echo "dirs: ${dirs_d}"
          echo "::set-output name=matrix::{\"dir\":[${dirs_d}]}"
      
      - run: echo ${{ steps.set-matrix.outputs.matrix }}
          

  


          
      
