# This is a basic workflow to help you get started with Actions

name: dba_artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # Identify the list of folders that need to be packaged into artifacts
  setup:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.set-dirs.outputs.dirs }}
      changes: ${{ steps.files.outputs.all }}
    steps:
      - uses: actions/checkout@v2
      
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
    
      - id: set-dirs
        name: Calculate directories to turn into artifacts
        run: |
          declare -a dirs
          for d in scripts/*/ ; do
            if [ ${d} == *"${{ steps.files.outputs.all }}"* ];
            then
                dirs+=("$d")
            fi
          done
          numDirs=${#dirs[@]}
          if [ numDirs -gt 1 ];
          then
            echo "You may not change more than 1 directory in a single PR. This one has ${numDirs} directory changes."
            exit 1
          fi
          if [ numDirs -eq 0 ];
          then
            echo "No changes to scripts directories."
            exit 0
          fi
          
      - uses: actions/upload-artifact@v3
        with:
          name: "zipfilefordbas"
          path: ${dirs[0]}
          

      

